openapi: 3.0.3
info:
  title: AMLscorer API
  version: 1.0.0
  description: |
    API for external CRM systems like Salesforce to interact with Apentis AMLscorer.

    Authentication via Bearer Token is required for all endpoints.

servers:
  - url: https://yourusername.github.io/amlscorer-api
    description: GitHub Pages hosting for AMLscorer API documentation

security:
  - bearerAuth: []

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Client:
      type: object
      required:
        - firstName
        - lastName
        - email
      properties:
        firstName:
          type: string
          description: Client's first name
        lastName:
          type: string
          description: Client's last name
        email:
          type: string
          format: email
          description: Client's email address
        birthDate:
          type: string
          format: date
          description: Date of birth (YYYY-MM-DD)
        nationality:
          type: string
          description: ISO 2-letter nationality code (e.g., 'US', 'FR')
        documentId:
          type: string
          description: External document ID reference

    UpdateClient:
      type: object
      properties:
        email:
          type: string
          format: email
          description: Updated client email address
        nationality:
          type: string
          description: Updated nationality code

    UploadDocumentResponse:
      type: object
      properties:
        documentId:
          type: string
        status:
          type: string

paths:
  /clients:
    post:
      summary: Create a new client
      tags:
        - Clients
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Client'
            example:
              firstName: "John"
              lastName: "Doe"
              email: "john.doe@example.com"
              birthDate: "1980-05-15"
              nationality: "US"
              documentId: "Passport123456"
      responses:
        '201':
          description: Client created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  clientId:
                    type: string
                  status:
                    type: string
              example:
                clientId: "abc123"
                status: "created"
        '400':
          description: Bad Request - Invalid input
        '401':
          description: Unauthorized - Missing or invalid token
        '500':
          description: Internal Server Error

  /clients/{clientId}:
    put:
      summary: Update an existing client
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: clientId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateClient'
      responses:
        '200':
          description: Client updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  clientId:
                    type: string
                  status:
                    type: string

  /clients/{clientId}/documents:
    post:
      summary: Upload a document for a client
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: clientId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                documentType:
                  type: string
                issueDate:
                  type: string
                  format: date
      responses:
        '201':
          description: Document uploaded successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UploadDocumentResponse'
