...

  /business-relations/{crmCode}:
    get:
      summary: Retrieve a business relation by crmCode
      tags:
        - Business Relations
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: crmCode
          required: true
          schema:
            type: string
          description: Unique external identifier of the business relation.
      responses:
        '200':
          description: Business relation retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BusinessRelation'
        '401':
          description: Unauthorized - Missing or invalid token
        '404':
          description: Not Found - Business relation not found
        '500':
          description: Internal Server Error

  /business-relations/{crmCode}/documents:
    get:
      summary: Retrieve documents associated with a business relation
      tags:
        - Documents
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: crmCode
          required: true
          schema:
            type: string
          description: Unique external identifier of the business relation.
      responses:
        '200':
          description: Documents retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DocumentMetadata'
        '401':
          description: Unauthorized - Missing or invalid token
        '404':
          description: Not Found - Business relation not found
        '500':
          description: Internal Server Error
